[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
jstz_crypto.workspace = true
tezos_crypto_rs.workspace = true
revm.workspace = true
alloy-sol-types.workspace = true
serde.workspace = true
bincode.workspace = true
