[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
tezos_crypto_rs.workspace = true
revm.workspace = true
alloy-sol-types.workspace = true
libsecp256k1.workspace = true
sha3.workspace = true
serde.workspace = true
bincode.workspace = true
